1.	Generate a tuple from the set ["aman", "222", 777, 400.4]

In [ ]:
tup = ("aman", "222", 777, 400.4)
print(tup)

('aman', '222', 777, 400.4)


2.	Create a dictionary of your basic data: (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys.

In [ ]:
myDict = {"roll_no": "CB.EN.U4CSE20205", "first_name": "Akshita Prasanth", "last_name": "Pallithodiyil", "dob": "04/11/2002"}
print(myDict)

{'roll_no': 'CB.EN.U4CSE20205', 'first_name': 'Akshita Prasanth', 'last_name': 'Pallithodiyil', 'dob': '04/11/2002'}


3.	Use rand function to generate a 2-dimensional random array with seed.

In [ ]:
from numpy import random
random.seed(0)
arr = random.randint(100, size = (2, 3))
print(arr)

[[44 47 64]
 [67 67  9]]


4.	Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)

In [ ]:
print(random.rand())
print(abs(-1234))

0.6235636967859723
1234


5.	Return a random integer N such that 20 <= N <= 90. 

In [ ]:
print(random.randint(20, 90))

56


6.	Given a population or set[11, 12, 13,14, 15]
*   Return a 3 length list of unique elements without replacement.
*   Shuffle the above set
*   Print a random number from the set

In [ ]:
import random as rd
my_set = [11, 12, 13, 14, 15]
l = rd.sample(my_set, 3)
print(l)
rd.shuffle(my_set)
print(my_set)
print(random.choice(my_set))

[15, 11, 12]
[14, 15, 13, 11, 12]
14


7.	Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.

In [ ]:
f = open('king.txt', 'w')
f.write("The King is Dead, Long Live The King")
f.close()
fi = open('king.txt', 'r')
fi.read()

'The King is Dead, Long Live The King'

8.	Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue. 

In [ ]:
def pos_neg(num):
  if num == 0:
    print("Number entered is 0.")
  elif num > 0:
    print(f'{num} is a positive number.')
  else:
    print(f'{num} is a negative number.')
number = int(input("Enter a number: "))
pos_neg(number)

Enter a number: 0
Number entered is 0.


In [ ]:
def loops(num):
  num_list = []
  for i in range(num):
    num_list.append(i)
  list_len = len(num_list)
  print(list_len)
  j = 0
  while j < list_len:
    if num_list[j] == 10:
      break
    elif num_list[j] % 2 == 0:
       print(num_list[j])
    j += 1
number = int(input("Enter a number: "))
loops(number)

Enter a number: 20
20
0
2
4
6
8


9.	Given a string "The King is Dead, Long Live The King".		
*   Print the complete string.
*   Print first character of the string.
*   Print characters starting from 3rd to 5th.
*   Print string starting from 3rd character.
*   Split the words.
*   An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements.




In [ ]:
str = "The King is Dead, Long Live The King"
print(str)
print(str[0])
print(str[3:6])
print(str[3:])
print(str.split(" "))
array = np.array([1, 4, 5, 8], dtype = "float")
print(array[1:3])

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']
[4. 5.]


10.	Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).

In [ ]:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


11.	Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).
*   Slice and display the 2nd row.
*   Write code to display as array([2., 5.]) 
*   Find the length of the array.

In [ ]:
print(arr1[1])
arr2 = np.array([2., 5.])
print(arr2)
print(arr1.size)

[4 5 6]
[2. 5.]
6


12.	Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array.

In [ ]:
np.random.seed(1)
arr3 = np.random.randint(100, size = 10)
print(arr3)
arr4 = arr3.reshape(5, 2)
print(arr4)
print(arr4.transpose())

[37 12 72  9 75  5 79 64 16  1]
[[37 12]
 [72  9]
 [75  5]
 [79 64]
 [16  1]]
[[37 72 75 79 16]
 [12  9  5 64  1]]


13.	Create an array from a list of 1, 2 and 3.

In [ ]:
arr5 = np.array([1, 2, 3])
print(arr5)

[1 2 3]


14.	Fill an array [1,2,3] with a single value [9,9,9]. 

In [ ]:
arr5 = [9 for x in arr5]
arr5

[9, 9, 9]

15.	Sum the elements of array [2,4,5].

In [ ]:
arr6 = np.array([2, 4, 5])
print(arr6.sum())

11


16.	Give the products of array [77,74,75]

In [ ]:
arr7 = np.array([77, 74, 75])
print(arr7.prod())

427350


17.	Given an array [2, 1, 9, 1, 2, 22, 1, 1, 4, 55, 6, 2, 56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.

In [ ]:
arr8 = np.array([2, 1, 9, 1, 2, 22, 1, 1, 4, 55, 6, 2, 56])
print(f'Mean: {arr8.mean()}')
print(f'Variance: {arr8.var()}')
print(f'Max: {arr8.max()}')
print(f'Min: {arr8.min()}')
print(f'Argmin: {arr8.argmin()}')
print(f'Argmax: {arr8.argmax()}')
print(f'Median: {np.median(arr8)}')
print(f'Standard deviation: {arr8.std()}')

Mean: 12.461538461538462
Variance: 367.32544378698225
Max: 56
Min: 1
Argmin: 1
Argmax: 12
Median: 2.0
Standard deviation: 19.165736192147232


18.	Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.

In [ ]:
arr9 = np.array([2, 1, 1, 4, 5, 5, 5, 7])
arr10 = np.unique(arr9)
arr10.sort()
print(arr10)

[1 2 4 5 7]


19.	Find dot product of two arrays [1, 2, 3] and [0, 1, 1]. 

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([0, 1, 2])
print(a1.dot(a2))

8


20.	Find the eigenvalues and eigenvectors of matrix A.

In [ ]:
a3 = np.array([[2, -12], [1, -5]])
eigen = np.linalg.eig(a3)
print(f'Eigenvalues: {eigen[0]}')
print(f'Eigenvectors: {eigen[1]}')

Eigenvalues: [-1. -2.]
Eigenvectors: [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


21. Given an array with [[11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients.

In [ ]:
a4 = np.array([[11, 22, 11, 31], [25, 33, 31, 28]], dtype = "float")
print(a4)
print(np.corrcoef(a4))

[[11. 22. 11. 31.]
 [25. 33. 31. 28.]]
[[1.         0.15997968]
 [0.15997968 1.        ]]
